version: '3'

volumes:
  lufi_data: {}

services:

  lufi:
    build:
      context: .
      dockerfile: lufi.dockerfile
    image: lufi
    ports:
      - 127.0.0.1:3024:8081
    volumes:
      - lufi_data:/var/lufi
      - ./lufi.passwd:/etc/lufi/lufi.passwd:ro
      - ./lufi.conf:/etc/lufi/lufi.conf:ro
    restart: unless-stopped
    depends_on:
      - sql

  sql:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_USER: lufi
      POSTGRES_PASSWORD:
    volumes:
      - "${MOUNT_SQL}:/var/lib/postgresql/data"

